hydra:
  output_subdir: null
  run:
    dir: ..

environment:
  SEED: 42

fitter:
  module: baselines.fitter
  type: Fitter
  config:
    train_frac: 0.25

    project_name: 'NODE model'
    experiment_name: 'DMD sin 42 SEED noise'
#    experiment_name: 'DMD sin 42 SEED no noise'
    notes: ''
    tags: ['DMD', 'final report', 'sin', '42 SEED', 'noise' ]
#    tags: ['DMD', 'final report', 'sin', '42 SEED', 'no noise' ]
    mode: 'online'


trajectory:
  module: src.data.data
  type: SinTrajectory
  config:
    noise_std: 0.1
#    noise_std: 0
    t0: 0
    T: 50.2654
    n_points: 802
    signal_amp: 1.


model:
  module: pydmd
  type: DMD
  config:
    svd_rank: 0
    tlsq_rank: 0
    exact: True
    opt: True
    rescale_mode: null
    forward_backward: False
    tikhonov_regularization: null

